from resources.Cooling import Cooling
from resources.Case import Case
from resources.Graphics import Graphics
from resources.Memory import Memory
from resources.Motherboard import Motherboard
from resources.PowerSupply import PowerSupply
from resources.Processor import Processor
from resources.Disk import Disk
from resources.Computer import Computer